scope:
#  domains: # registered domain names in scope
#    - owasp.org
#  ips: # IP addresses in scope, multiple methods of inserting IP addresses can be used
#    - 192.0.2.1
#    - 192.0.2.2
#    - 192.168.0.3-8
#    - 192.168.0.10-192.168.0.20
#  cidrs: # CIDR ranges that are in scope
#    - 192.0.2.0/24
#    - 192.0.2.128/25
  ports: # ports to be used when actively scanning services
    - 80
    - 443
    - 8000
    - 8080
    - 8443
    - 8888
#  blacklist: # subdomains to be blacklisted
#    - example.owasp.org
options:
  datasources: "./datasources.yaml"
  engine: "http://engine:4000/graphql"
  # be sure to set your username and password in the following URI to the 
  # AMASS_USER and AMASS_PASSWORD values, respectively, in your .env file
  # database: "bolt://neo4j:amass4OWASP@neo4j:7687/neo4j"
  database: "postgres://amass:amass4OWASP@assetdb:5432/assetdb"
  bruteforce:
    enabled: false
    wordlists: # wordlist(s) to use that are specific to brute forcing
      - "./wordlists/short-wordlist.txt"
      #- "./wordlists/subdomains-top1mil-5000.txt"
      #- "./wordlists/subdomains-top1mil-20000.txt"
      #- "./wordlists/subdomains-top1mil-110000.txt"
  alterations:
    enabled: false
    wordlists: # wordlist(s) to use that are specific to name alterations
      - "./wordlists/alterations.txt"
  default_transform_values: # default, global values for transformations, if not specified in the transformation.
    ttl: 10080 # default is 1440
    confidence: 50 # default is 50
    priority: 5 # default global priority is 5 (assuming its 1-10)

transformations:
  ContactRecord->ALL:
  DomainRecord->ALL:
  FQDN->FQDN:
  FQDN->IPAddress:
  Identifier->ALL:
  IPAddress->FQDN:
  IPAddress->Netblock:
  IPAddress->ASN:
  IPAddress->RIROrg:
  Location->ALL:
  Netblock->ALL:
  Organization->ALL:
  Person->ALL:
  Phone->ALL:
  TLSCertificate->ALL:
  URL->ALL:
